#!/usr/bin/env bash
# install.sh — bootstrap devtools in a consuming repo
#
# Usage:
#   Via submodule:  bash .devtools/scripts/install.sh
#   Via curl:        curl -sSL https://raw.githubusercontent.com/ostara-labs/devtools/v1/scripts/install.sh | bash
#
# What it does:
#   1. Configures git core.hooksPath to use devtools hooks
#   2. Creates a minimal Makefile if none exists (or appends include if one exists)
#   3. Copies language-appropriate lint configs if not present
#
# Exit 0 = success, exit 1 = error.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$(pwd)")"
DEVTOOLS_DIR=""

# --- Locate devtools directory ---
if [ -d "$REPO_ROOT/.devtools" ]; then
  DEVTOOLS_DIR="$REPO_ROOT/.devtools"
elif [ -d "$REPO_ROOT/devtools" ]; then
  DEVTOOLS_DIR="$REPO_ROOT/devtools"
else
  echo "[install] Error: devtools directory not found."
  echo "[install] Add it as a submodule: git submodule add https://github.com/ostara-labs/devtools .devtools"
  echo "[install] Or clone it: git clone https://github.com/ostara-labs/devtools .devtools"
  exit 1
fi

echo "[install] devtools found at: $DEVTOOLS_DIR"

# --- 1. Configure git hooks ---
HOOKS_DIR="$DEVTOOLS_DIR/hooks"
if [ -d "$HOOKS_DIR" ]; then
  git config core.hooksPath "$HOOKS_DIR"
  chmod +x "$HOOKS_DIR"/* 2>/dev/null || true
  echo "[install] git hooksPath set to: $HOOKS_DIR"
else
  echo "[install] Warning: hooks directory not found at $HOOKS_DIR"
fi

# --- 2. Create or update Makefile ---
MAKEFILE="$REPO_ROOT/Makefile"

# Detect language
LANG_TARGET=""
if [ -f "$REPO_ROOT/Cargo.toml" ]; then
  LANG_TARGET="rust"
elif [ -f "$REPO_ROOT/mix.exs" ]; then
  LANG_TARGET="elixir"
elif [ -f "$REPO_ROOT/package.json" ]; then
  LANG_TARGET="typescript"
fi

if [ -n "$LANG_TARGET" ]; then
  INCLUDE_LINE="include .devtools/makefiles/Makefile.${LANG_TARGET}"

  if [ ! -f "$MAKEFILE" ]; then
    # Create a minimal Makefile
    cat > "$MAKEFILE" << EOF
# Makefile — auto-generated by devtools install.sh
# Language: ${LANG_TARGET}
# Standard targets: make lint, make test, make build, make ci, make format, make clean, make help

${INCLUDE_LINE}

# Add repo-specific targets below
EOF
    echo "[install] Created Makefile with ${LANG_TARGET} targets."
  else
    # Check if the include already exists
    if grep -q "Makefile.${LANG_TARGET}" "$MAKEFILE"; then
      echo "[install] Makefile already includes devtools ${LANG_TARGET} targets."
    else
      # Append the include
      echo "" >> "$MAKEFILE"
      echo "# --- devtools standard targets ---" >> "$MAKEFILE"
      echo "$INCLUDE_LINE" >> "$MAKEFILE"
      echo "[install] Appended devtools ${LANG_TARGET} include to existing Makefile."
    fi
  fi
else
  echo "[install] No language detected (no Cargo.toml, mix.exs, or package.json). Skipping Makefile setup."
fi

# --- 3. Copy lint configs (if not present) ---
CONFIGS_DIR="$DEVTOOLS_DIR/configs"

copy_config() {
  local config_file="$1"
  local dest="$2"
  if [ -f "$CONFIGS_DIR/$config_file" ] && [ ! -f "$dest" ]; then
    cp "$CONFIGS_DIR/$config_file" "$dest"
    echo "[install] Copied $config_file to repo root."
  fi
}

if [ "$LANG_TARGET" = "rust" ]; then
  copy_config "clippy.toml" "$REPO_ROOT/clippy.toml"
  copy_config "rustfmt.toml" "$REPO_ROOT/rustfmt.toml"
elif [ "$LANG_TARGET" = "typescript" ]; then
  copy_config "biome.json" "$REPO_ROOT/biome.json"
fi

# --- Done ---
echo ""
echo "[install] Done! Available make targets:"
if [ -f "$MAKEFILE" ]; then
  cd "$REPO_ROOT" && make help 2>/dev/null || true
fi
echo ""
echo "[install] Git hooks are active. Test with: git commit --dry-run"
