# install.ps1 — bootstrap devtools in a consuming repo (Windows PowerShell)
#
# Usage:
#   Via submodule:  powershell -File .devtools\scripts\install.ps1
#
# What it does:
#   1. Configures git core.hooksPath to use devtools hooks
#   2. Creates a minimal Makefile if none exists (or appends include if one exists)
#   3. Copies language-appropriate lint configs if not present

param(
    [string]$RepoRoot = ""
)

$ErrorActionPreference = "Stop"

if (-not $RepoRoot) {
    $RepoRoot = git rev-parse --show-toplevel 2>$null
    if (-not $RepoRoot) { $RepoRoot = (Get-Location).Path }
}

$DevtoolsDir = ""

# --- Locate devtools directory ---
if (Test-Path "$RepoRoot\.devtools") {
    $DevtoolsDir = "$RepoRoot\.devtools"
} elseif (Test-Path "$RepoRoot\devtools") {
    $DevtoolsDir = "$RepoRoot\devtools"
} else {
    Write-Host "[install] Error: devtools directory not found."
    Write-Host "[install] Add it as a submodule: git submodule add https://github.com/ostara-labs/devtools .devtools"
    exit 1
}

Write-Host "[install] devtools found at: $DevtoolsDir"

# --- 1. Configure git hooks ---
$HooksDir = "$DevtoolsDir\hooks"
if (Test-Path $HooksDir) {
    git config core.hooksPath $HooksDir.Replace('\', '/')
    Write-Host "[install] git hooksPath set to: $HooksDir"
} else {
    Write-Host "[install] Warning: hooks directory not found at $HooksDir"
}

# --- 2. Create or update Makefile ---
$Makefile = "$RepoRoot\Makefile"

# Detect language
$LangTarget = ""
if (Test-Path "$RepoRoot\Cargo.toml") {
    $LangTarget = "rust"
} elseif (Test-Path "$RepoRoot\mix.exs") {
    $LangTarget = "elixir"
} elseif (Test-Path "$RepoRoot\package.json") {
    $LangTarget = "typescript"
}

if ($LangTarget) {
    $IncludeLine = "include .devtools/makefiles/Makefile.$LangTarget"

    if (-not (Test-Path $Makefile)) {
        # Create a minimal Makefile
        $content = @"
# Makefile -- auto-generated by devtools install.ps1
# Language: $LangTarget
# Standard targets: make lint, make test, make build, make ci, make format, make clean, make help

$IncludeLine

# Add repo-specific targets below
"@
        Set-Content -Path $Makefile -Value $content -Encoding UTF8
        Write-Host "[install] Created Makefile with $LangTarget targets."
    } else {
        $existing = Get-Content $Makefile -Raw
        if ($existing -match "Makefile.$LangTarget") {
            Write-Host "[install] Makefile already includes devtools $LangTarget targets."
        } else {
            Add-Content -Path $Makefile -Value "`n# --- devtools standard targets ---`n$IncludeLine"
            Write-Host "[install] Appended devtools $LangTarget include to existing Makefile."
        }
    }
} else {
    Write-Host "[install] No language detected. Skipping Makefile setup."
}

# --- 3. Copy lint configs ---
$ConfigsDir = "$DevtoolsDir\configs"

function Copy-Config {
    param($ConfigFile, $Dest)
    $src = "$ConfigsDir\$ConfigFile"
    if ((Test-Path $src) -and -not (Test-Path $Dest)) {
        Copy-Item $src $Dest
        Write-Host "[install] Copied $ConfigFile to repo root."
    }
}

if ($LangTarget -eq "rust") {
    Copy-Config "clippy.toml" "$RepoRoot\clippy.toml"
    Copy-Config "rustfmt.toml" "$RepoRoot\rustfmt.toml"
} elseif ($LangTarget -eq "typescript") {
    Copy-Config "biome.json" "$RepoRoot\biome.json"
}

Write-Host ""
Write-Host "[install] Done! Git hooks are active."
